# Generated by Django 3.2.11 on 2022-01-07 15:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActorModel',
            fields=[
                ('unique_key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'survey actor',
                'verbose_name_plural': 'survey actors',
                'db_table': 'api_actors',
            },
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('one', 'Only one answer'), ('many', 'Many answers'), ('text', 'Text answer')])),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'db_table': 'api_questions',
            },
        ),
        migrations.CreateModel(
            name='SurveyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('begin_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'survey',
                'verbose_name_plural': 'surveys',
                'db_table': 'api_surveys',
            },
        ),
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('unique_key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='survey.actormodel')),
            ],
            options={
                'verbose_name': 'survey session',
                'verbose_name_plural': 'survey sessions',
                'db_table': 'api_sessions',
            },
        ),
        migrations.CreateModel(
            name='ResponseOptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_options', to='survey.questionmodel')),
            ],
            options={
                'verbose_name': 'response option',
                'verbose_name_plural': 'response options',
                'db_table': 'api_response_options',
            },
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.surveymodel'),
        ),
        migrations.CreateModel(
            name='AnswerActModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_acts', to='survey.responseoptionmodel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_acts', to='survey.sessionmodel')),
            ],
            options={
                'verbose_name': 'answer act',
                'verbose_name_plural': 'answer acts',
                'db_table': 'api_answer_acts',
            },
        ),
    ]
